version: '2'

# Define the services/containers to be run
services:
    angular:
        build: ../Pneuma
        ports:
            - "4200:4200"

    database:
        image: mongo
        ports:
            - "27017:27017"