version: '2'

# Define the services/containers to be run
services:
    angular:
        build: ../../Pneuma
        ports:
            - "4200:4200"
            - "49153:49153"

    database:
        image: mongo
        ports:
            - "27017:27017"

    redis:
        image: redis
        ports:
            - "6379:6379"